// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwfexqrguylfxdwupebg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3ZmV4cXJndXlsZnhkd3VwZWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MjAwMzksImV4cCI6MjA1NTM5NjAzOX0.CmJLFUa_2_FrMxWg43DjSwemEtKXWYB_P-H6pNXJkyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);